ALTER TABLE donaciones
    MODIFY COLUMN monto DECIMAL(10,2) NOT NULL,
    MODIFY COLUMN metodo_pago ENUM(
        'EFECTIVO',
        'TRANSFERENCIA',
        'PAYPAL'
    ) NOT NULL,
    MODIFY COLUMN fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN estatus ENUM(
        'PENDIENTE',
        'COMPLETADA',
        'CANCELADA'
    ) NOT NULL DEFAULT 'PENDIENTE',
    MODIFY COLUMN usuario_id BIGINT NOT NULL,
    MODIFY COLUMN refugio_id BIGINT NOT NULL;